[profile.default]
libs = ["../../lib"]
auto_detect_remappings = false
remappings = [
  "@openzeppelin/contracts/=../../lib/openzeppelin-contracts/contracts/",
  "openzeppelin-contracts/=../../lib/openzeppelin-contracts/",
  "forge-std/=../../lib/forge-std/src/"
]
